# Python Programming Basic Assignment
### Assignment 8

[1] Write a Python Program to Add Two Matrices?

In [1]:
x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

import numpy as np

result = np.add(x, y)

print(result)


[[17 15  4]
 [10 12  9]
 [11 13 18]]


[2] Write a Python Program to Multiply Two Matrices?

In [2]:
x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

import numpy as np

result = np.multiply(x, y)

print(result)

[[60 56  3]
 [24 35 18]
 [28 40 81]]


[3] Write a Python Program to Transpose a Matrix?

In [3]:
x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

import numpy as np

result = np.transpose(x)
print(result)

[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]


[4] Write a Python Program to Sort Words in Alphabetic Order?

In [5]:
words = ['Ramesh', 'Mahesh', 'Dinesh', 'Suresh']

words.sort()

print(words)

['Dinesh', 'Mahesh', 'Ramesh', 'Suresh']


[5] Write a Python Program to Remove Punctuation From a String?

In [6]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, how are you./;."

for c in my_str:
    if c not in punctuations:
        print(c, end='')

Hello how are you